esphome:
  name: blinds1
  platform: ESP32
  board: esp-wrover-kit
  includes:
    - customcover.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

cover:
- platform: custom
  lambda: |-
    auto my_custom_cover = new MyCustomCover();
    App.register_component(my_custom_cover);
    return {my_custom_cover};

  covers:
    - name: "My Custom Cover"